### ISSUE TITLE
502 Bad Gateway Error

### ISSUE THREAD

**Issue by miklb** [tillkruss/Nginx-FastCGI-Cache#16]
I'm seeing this error `PHP Warning:  Invalid argument supplied for foreach() in //plugins/Nginx-FastCGI-Cache/nginx-cache.php on line 198`

And getting a 502 bad gateway error along with `upstream sent too big header while reading response`

This is my conf for fastcgi which I thought was related
```
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_cache_valid 60m;
        proxy_buffer_size   128k;
        proxy_buffers   4 256k;
        proxy_busy_buffers_size   256k;
```

Any suggestions greatly appreciated.

**Comment by tillkruss** [comment]
I've fixed that in https://github.com/tillkruss/Nginx-FastCGI-Cache/commit/7e5d67048c2e25aac58212afb28259e2ba103929.

Could you download the master version of this plugin and see if that worked?

**Comment by miklb** [comment]
Looks like the error moved to 207. Also, looking through query-monitor, looks like I've still not sorted out the correct permissions for my `/cache` directory which *might* be related? I'm not getting an error with the plugin for File Permissions API however.

**Comment by tillkruss** [comment]
Same error? Can you try master: https://github.com/tillkruss/Nginx-FastCGI-Cache/archive/master.zip

**Comment by tillkruss** [comment]
Directory permissions might be related, but I'd like the plugin to tell you that without crashing.

**Comment by miklb** [comment]
I'm checking out at CLI from this repo's master branch. I'm game to help debug as much as I can.

**Comment by tillkruss** [comment]
Could you post the PHP error?

**Comment by miklb** [comment]
`Invalid argument supplied for foreach() content/plugins/Nginx-FastCGI-Cache/nginx-cache.php:207`

**Comment by tillkruss** [comment]
`var_dump($list); exit;` in line 206 please?

**Comment by miklb** [comment]
Sorry, GitHub choked on the copy/paste so adding as a file
[var_dump.txt](https://github.com/tillkruss/Nginx-FastCGI-Cache/files/1599194/var_dump.txt)

**Comment by tillkruss** [comment]
That should work. Maybe it's being called several times.

Maybe just try fixing the permissions for your Nginx cache path.

**Comment by miklb** [comment]
I just cleaned up 2 more directory permissions inside my cache and now not getting the error. I'll keep an eye out, still not seeing the Filesystem error I was getting before. 
Either way, thanks for the quick response and your work on this plugin.
